name: CI

on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install Qt5
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        arch: 'win64_msvc2019_64'
        # Only download what is necessary to reduce network failure risk
        modules: 'qtbase qtsvg qttools' 
        use-official: 'true'

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      run: choco install ninja

    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Ninja" `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_PREFIX_PATH="${{ env.Qt5_Dir }}"

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: chessx-windows-binaries
        path: |
          build/*.exe
          build/release/*.exe
